// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_arch/data/models/projedetaymodel/projedetay_model.dart';
import 'package:flutter_arch/data/models/projemodel/proje_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProjeAdapter());
    registerAdapter(ProjeDetayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ProjeAdapter());
    registerAdapter(ProjeDetayAdapter());
  }
}
